import type { BankWord, Position } from "../types";

export const words: Record<Position, BankWord[]> = {
  initial: [
    { word: "kalem", syllableBreak: "ka-lem", visualPrompt: "a yellow pencil" },
    { word: "kedi", syllableBreak: "ke-di", visualPrompt: "a cat" },
    { word: "kapı", syllableBreak: "ka-pı", visualPrompt: "a wooden door" },
    { word: "kuş", syllableBreak: "kuş", visualPrompt: "a small bird perched on a branch" },
    { word: "karpuz", syllableBreak: "kar-puz", visualPrompt: "a whole watermelon" },
    { word: "kelebek", syllableBreak: "ke-le-bek", visualPrompt: "a colorful butterfly" },
    { word: "kitap", syllableBreak: "ki-tap", visualPrompt: "an open book" },
    { word: "kova", syllableBreak: "ko-va", visualPrompt: "a plastic bucket" },
    { word: "kavun", syllableBreak: "ka-vun", visualPrompt: "a yellow cantaloupe melon" },
    { word: "kaşık", syllableBreak: "ka-şık", visualPrompt: "a wooden spoon" },
    { word: "kafes", syllableBreak: "ka-fes", visualPrompt: "a metal bird cage" },
    { word: "kalp", syllableBreak: "kalp", visualPrompt: "a red heart shape" },
    { word: "kamyon", syllableBreak: "kam-yon", visualPrompt: "a large truck" },
    { word: "kanat", syllableBreak: "ka-nat", visualPrompt: "a bird wing" },
    { word: "kar", syllableBreak: "kar", visualPrompt: "snow on the ground" },
    { word: "kasa", syllableBreak: "ka-sa", visualPrompt: "a wooden crate box" },
    { word: "kazak", syllableBreak: "ka-zak", visualPrompt: "a knitted wool sweater" },
    { word: "kek", syllableBreak: "kek", visualPrompt: "a small round cake" },
    { word: "keman", syllableBreak: "ke-man", visualPrompt: "a violin" },
    { word: "kepçe", syllableBreak: "kep-çe", visualPrompt: "a soup ladle" },
    { word: "kiraz", syllableBreak: "ki-raz", visualPrompt: "a pair of red cherries" },
    { word: "köpek", syllableBreak: "kö-pek", visualPrompt: "a dog" },
    { word: "köprü", syllableBreak: "köp-rü", visualPrompt: "a stone bridge" },
    { word: "kurbağa", syllableBreak: "kur-ba-ğa", visualPrompt: "a green frog" },
    { word: "kutu", syllableBreak: "ku-tu", visualPrompt: "a cardboard box" },
    { word: "kürek", syllableBreak: "kü-rek", visualPrompt: "a garden shovel" },
    { word: "kömür", syllableBreak: "kö-mür", visualPrompt: "a piece of black coal" },
    { word: "kavak", syllableBreak: "ka-vak", visualPrompt: "a tall poplar tree" },
    { word: "kayak", syllableBreak: "ka-yak", visualPrompt: "a ski on snow" },
    { word: "kuzu", syllableBreak: "ku-zu", visualPrompt: "a small white lamb" },
  ],
  medial: [
    // "k" appears in word.slice(1,-1) — not the first character, not the last character
    { word: "makas", syllableBreak: "ma-kas", visualPrompt: "a pair of scissors" },
    { word: "bisiklet", syllableBreak: "bi-sik-let", visualPrompt: "a bicycle" },
    { word: "çikolata", syllableBreak: "çi-ko-la-ta", visualPrompt: "a chocolate bar" },
    { word: "çakal", syllableBreak: "ça-kal", visualPrompt: "a jackal" },
    { word: "iskele", syllableBreak: "is-ke-le", visualPrompt: "a wooden dock pier" },
    { word: "lokum", syllableBreak: "lo-kum", visualPrompt: "a piece of Turkish delight" },
    { word: "paket", syllableBreak: "pa-ket", visualPrompt: "a wrapped package" },
    { word: "rakam", syllableBreak: "ra-kam", visualPrompt: "a number digit written on paper" },
    { word: "sekiz", syllableBreak: "se-kiz", visualPrompt: "the numeral 8 on a card" },
    { word: "takvim", syllableBreak: "tak-vim", visualPrompt: "a wall calendar" },
    { word: "yaka", syllableBreak: "ya-ka", visualPrompt: "a shirt collar" },
    { word: "baklava", syllableBreak: "bak-la-va", visualPrompt: "a diamond-shaped honey pastry" },
    { word: "çakıl", syllableBreak: "ça-kıl", visualPrompt: "small pebble stones" },
    { word: "iskelet", syllableBreak: "is-ke-let", visualPrompt: "a human skeleton" },
    { word: "kaktüs", syllableBreak: "kak-tüs", visualPrompt: "a green cactus plant in a pot" },
    { word: "makine", syllableBreak: "ma-ki-ne", visualPrompt: "a sewing machine" },
    { word: "balkon", syllableBreak: "bal-kon", visualPrompt: "a balcony with a metal railing" },
    { word: "çekiç", syllableBreak: "çe-kiç", visualPrompt: "a metal hammer" },
    { word: "mikrodalga", syllableBreak: "mik-ro-dal-ga", visualPrompt: "a microwave oven" },
    { word: "okul", syllableBreak: "o-kul", visualPrompt: "a school building" },
    { word: "taksi", syllableBreak: "tak-si", visualPrompt: "a yellow taxi cab" },
    { word: "akrep", syllableBreak: "ak-rep", visualPrompt: "a scorpion" },
    { word: "çakma", syllableBreak: "çak-ma", visualPrompt: "a cigarette lighter" },
    { word: "şakayık", syllableBreak: "şa-ka-yık", visualPrompt: "a pink peony flower" },
    { word: "ekmek", syllableBreak: "ek-mek", visualPrompt: "a loaf of bread" },
    { word: "çiklet", syllableBreak: "çik-let", visualPrompt: "a stick of chewing gum" },
    { word: "çıkrık", syllableBreak: "çık-rık", visualPrompt: "a wooden spinning wheel" },
    { word: "dekor", syllableBreak: "de-kor", visualPrompt: "a decorated room interior" },
    { word: "çukur", syllableBreak: "çu-kur", visualPrompt: "a hole dug in the ground" },
    { word: "tıkaç", syllableBreak: "tı-kaç", visualPrompt: "a rubber stopper plug" },
  ],
  final: [
    // every word ends with "k"
    { word: "balık", syllableBreak: "ba-lık", visualPrompt: "a fish" },
    { word: "ayak", syllableBreak: "a-yak", visualPrompt: "a bare human foot" },
    { word: "çiçek", syllableBreak: "çi-çek", visualPrompt: "a red flower" },
    { word: "ekmek", syllableBreak: "ek-mek", visualPrompt: "a loaf of bread" },
    { word: "tabak", syllableBreak: "ta-bak", visualPrompt: "a round ceramic plate" },
    { word: "bardak", syllableBreak: "bar-dak", visualPrompt: "a drinking glass" },
    { word: "böcek", syllableBreak: "bö-cek", visualPrompt: "a beetle insect" },
    { word: "inek", syllableBreak: "i-nek", visualPrompt: "a cow" },
    { word: "ipek", syllableBreak: "i-pek", visualPrompt: "a shiny silk fabric swatch" },
    { word: "kaşık", syllableBreak: "ka-şık", visualPrompt: "a spoon" },
    { word: "kemik", syllableBreak: "ke-mik", visualPrompt: "a white bone" },
    { word: "kulak", syllableBreak: "ku-lak", visualPrompt: "a human ear" },
    { word: "bebek", syllableBreak: "be-bek", visualPrompt: "a baby" },
    { word: "bilek", syllableBreak: "bi-lek", visualPrompt: "a human wrist" },
    { word: "gözlük", syllableBreak: "göz-lük", visualPrompt: "a pair of eyeglasses" },
    { word: "köpek", syllableBreak: "kö-pek", visualPrompt: "a dog" },
    { word: "kürek", syllableBreak: "kü-rek", visualPrompt: "a garden shovel" },
    { word: "yürek", syllableBreak: "yü-rek", visualPrompt: "a heart organ" },
    { word: "yastık", syllableBreak: "yas-tık", visualPrompt: "a bed pillow" },
    { word: "yüzük", syllableBreak: "yü-zük", visualPrompt: "a gold ring" },
    { word: "çomak", syllableBreak: "ço-mak", visualPrompt: "a wooden stick club" },
    { word: "kazak", syllableBreak: "ka-zak", visualPrompt: "a knitted wool sweater" },
    { word: "elmacık", syllableBreak: "el-ma-cık", visualPrompt: "a small red apple" },
    { word: "çilek", syllableBreak: "çi-lek", visualPrompt: "a red strawberry" },
    { word: "boncuk", syllableBreak: "bon-cuk", visualPrompt: "a glass bead" },
    { word: "kabak", syllableBreak: "ka-bak", visualPrompt: "a round green zucchini" },
    { word: "eşek", syllableBreak: "e-şek", visualPrompt: "a donkey" },
    { word: "kazık", syllableBreak: "ka-zık", visualPrompt: "a pointed wooden stake" },
    { word: "böbrek", syllableBreak: "böb-rek", visualPrompt: "a kidney organ" },
    { word: "parmak", syllableBreak: "par-mak", visualPrompt: "a pointing finger" },
  ],
};
