import type { BankWord, Position } from "../types";

// Phonotactic notes for /r/:
// - initial: RARE in native Turkish — only common loanwords; ~10 honest entries
// - medial: RICH position in Turkish — 30 entries
// - final: RICH position in Turkish — 27 entries

export const words: Record<Position, BankWord[]> = {
  initial: [
    // Native Turkish words almost never begin with "r"; these are all established loanwords
    { word: "radyo", syllableBreak: "rad-yo", visualPrompt: "a vintage radio device" },
    { word: "robot", syllableBreak: "ro-bot", visualPrompt: "a toy robot" },
    { word: "roket", syllableBreak: "ro-ket", visualPrompt: "a rocket ship launching" },
    { word: "rende", syllableBreak: "ren-de", visualPrompt: "a metal kitchen grater" },
    { word: "reçel", syllableBreak: "re-çel", visualPrompt: "a jar of fruit jam" },
    { word: "ruj", syllableBreak: "ruj", visualPrompt: "a red lipstick tube" },
    { word: "ring", syllableBreak: "ring", visualPrompt: "a boxing ring" },
    { word: "resim", syllableBreak: "re-sim", visualPrompt: "a framed picture on a wall" },
    { word: "renk", syllableBreak: "renk", visualPrompt: "a row of paint color swatches" },
    { word: "rampa", syllableBreak: "ram-pa", visualPrompt: "a vehicle loading ramp" },
  ],
  medial: [
    // "r" appears in word.slice(1,-1) — not the first or last character
    { word: "araba", syllableBreak: "a-ra-ba", visualPrompt: "a red toy car" },
    { word: "marul", syllableBreak: "ma-rul", visualPrompt: "a head of lettuce" },
    { word: "karpuz", syllableBreak: "kar-puz", visualPrompt: "a whole watermelon" },
    { word: "portakal", syllableBreak: "por-ta-kal", visualPrompt: "an orange fruit" },
    { word: "fırça", syllableBreak: "fır-ça", visualPrompt: "a toothbrush" },
    { word: "tornavida", syllableBreak: "tor-na-vi-da", visualPrompt: "a screwdriver" },
    { word: "sarımsak", syllableBreak: "sa-rım-sak", visualPrompt: "a head of garlic" },
    { word: "karınca", syllableBreak: "ka-rın-ca", visualPrompt: "a small red ant" },
    { word: "turp", syllableBreak: "turp", visualPrompt: "a white radish root" },
    { word: "armut", syllableBreak: "ar-mut", visualPrompt: "a pear fruit" },
    { word: "kirpi", syllableBreak: "kir-pi", visualPrompt: "a hedgehog with spines" },
    { word: "terlik", syllableBreak: "ter-lik", visualPrompt: "a pair of slippers" },
    { word: "dürüm", syllableBreak: "dü-rüm", visualPrompt: "a rolled wrap sandwich" },
    { word: "yorgan", syllableBreak: "yor-gan", visualPrompt: "a thick quilt blanket" },
    { word: "serçe", syllableBreak: "ser-çe", visualPrompt: "a small sparrow bird" },
    { word: "mercan", syllableBreak: "mer-can", visualPrompt: "a piece of red coral" },
    { word: "burgu", syllableBreak: "bur-gu", visualPrompt: "a hand drill auger tool" },
    { word: "örümcek", syllableBreak: "ö-rüm-cek", visualPrompt: "a spider" },
    { word: "çarşaf", syllableBreak: "çar-şaf", visualPrompt: "a bed sheet" },
    { word: "fırın", syllableBreak: "fı-rın", visualPrompt: "a kitchen oven" },
    { word: "martı", syllableBreak: "mar-tı", visualPrompt: "a seagull in flight" },
    { word: "ördek", syllableBreak: "ör-dek", visualPrompt: "a duck swimming on water" },
    { word: "turna", syllableBreak: "tur-na", visualPrompt: "a crane bird standing tall" },
    { word: "çorba", syllableBreak: "çor-ba", visualPrompt: "a bowl of hot soup" },
    { word: "kartal", syllableBreak: "kar-tal", visualPrompt: "an eagle soaring in the sky" },
    { word: "kurşun", syllableBreak: "kur-şun", visualPrompt: "a grey lead pencil tip" },
    { word: "mercimek", syllableBreak: "mer-ci-mek", visualPrompt: "a pile of red lentils" },
    { word: "tırnak", syllableBreak: "tır-nak", visualPrompt: "a painted fingernail" },
    { word: "çerçeve", syllableBreak: "çer-çe-ve", visualPrompt: "a wooden picture frame" },
    { word: "çırpı", syllableBreak: "çır-pı", visualPrompt: "a bundle of dry twigs" },
  ],
  final: [
    // every word ends with "r"
    { word: "kar", syllableBreak: "kar", visualPrompt: "snow on the ground" },
    { word: "mor", syllableBreak: "mor", visualPrompt: "a purple color swatch" },
    { word: "nar", syllableBreak: "nar", visualPrompt: "a pomegranate" },
    { word: "demir", syllableBreak: "de-mir", visualPrompt: "an iron metal bar" },
    { word: "şeker", syllableBreak: "şe-ker", visualPrompt: "a white sugar cube" },
    { word: "duvar", syllableBreak: "du-var", visualPrompt: "a brick wall" },
    { word: "anahtar", syllableBreak: "a-nah-tar", visualPrompt: "a metal house key" },
    { word: "fener", syllableBreak: "fe-ner", visualPrompt: "a handheld lantern" },
    { word: "çember", syllableBreak: "çem-ber", visualPrompt: "a plastic hula hoop" },
    { word: "kömür", syllableBreak: "kö-mür", visualPrompt: "a piece of black coal" },
    { word: "motor", syllableBreak: "mo-tor", visualPrompt: "a car engine" },
    { word: "tomar", syllableBreak: "to-mar", visualPrompt: "a rolled paper scroll" },
    { word: "şehir", syllableBreak: "şe-hir", visualPrompt: "a city skyline with buildings" },
    { word: "asker", syllableBreak: "as-ker", visualPrompt: "a toy soldier figurine" },
    { word: "bahar", syllableBreak: "ba-har", visualPrompt: "a bunch of spring flowers" },
    { word: "nehir", syllableBreak: "ne-hir", visualPrompt: "a flowing river" },
    { word: "kemer", syllableBreak: "ke-mer", visualPrompt: "a leather belt" },
    { word: "hıyar", syllableBreak: "hı-yar", visualPrompt: "a green cucumber vegetable" },
    { word: "mantar", syllableBreak: "man-tar", visualPrompt: "a mushroom" },
    { word: "semer", syllableBreak: "se-mer", visualPrompt: "a donkey saddle" },
    { word: "vapur", syllableBreak: "va-pur", visualPrompt: "a passenger ferry boat" },
    { word: "çınar", syllableBreak: "çı-nar", visualPrompt: "a huge majestic old plane tree with a thick trunk and broad green canopy" },
    { word: "pınar", syllableBreak: "pı-nar", visualPrompt: "a natural spring water source" },
    { word: "katar", syllableBreak: "ka-tar", visualPrompt: "a train of railroad cars" },
    { word: "tamir", syllableBreak: "ta-mir", visualPrompt: "a set of repair tools" },
    { word: "semaver", syllableBreak: "se-ma-ver", visualPrompt: "a traditional samovar tea urn" },
    { word: "çadır", syllableBreak: "ça-dır", visualPrompt: "a camping tent" },
  ],
};
